name: Sync LeetCode
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        # 换成这个专门支持力扣中国站的仓库，使用 main 分支
        uses: haloiscoding/leetcode-sync@main  
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: 'solutions'
          leetcode-cn: true                # 确保这里是 true
