name: Sync LeetCode
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        # 适配中国站且目前维护最及时的版本
        uses: gear-gear/leetcode-sync@master  
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: 'solutions'
          # 注意：这个插件的参数名可能略有不同
          leetcode-cn: true
